Repository AY2324S2-CS2113-W14-2/tp, pull requests merged in 2024-03, with the labels that each got.

#16 Fix missing end brace bug line 40 of RecipeIOTest
  src/test/java/recipeio/RecipeIOTest.java
Labels: type.Bug, severity.High

#22 Add Save file and Load file methods
  recipe.txt
  src/main/java/storage/Storage.java
  src/test/java/storage/StorageTest.java
Labels: priority.High

#64 Add basic details to Developer Guide
  docs/DeveloperGuide.md
Labels: type.Task, priority.Medium

#65 Add custom exceptions, handle invalid index passed into delete function
  src/main/java/recipeio/Constants.java
  src/main/java/recipeio/InputParser.java
  src/main/java/recipeio/RecipeIO.java
  src/main/java/recipeio/commands/DeleteRecipeCommand.java
  src/main/java/recipeio/exceptions/EmptyIndexException.java
  src/main/java/recipeio/exceptions/InvalidDescriptionException.java
  src/main/java/recipeio/exceptions/InvalidIndexException.java
  src/main/java/recipeio/recipe/RecipeList.java
  src/main/java/recipeio/ui/UI.java
  src/test/java/recipeio/RecipeIOTest.java
  src/test/java/ui/UITest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Task, priority.Medium

#70 Branch fix find
  src/main/java/recipeio/commands/FindCommand.java
Labels: type.Bug, priority.High, severity.High

#71 Modify DG
  docs/DeveloperGuide.md
Labels: documentation

#91 Add Java doc and comments
  docs/DeveloperGuide.md
  src/main/java/recipeio/CommandValidator.java
  src/main/java/recipeio/RecipeIO.java
  src/main/java/recipeio/commands/DeleteRecipeCommand.java
  src/main/java/recipeio/commands/FilterByAllergyCommand.java
  src/main/java/recipeio/commands/ListRecipeCommand.java
  src/main/java/recipeio/commands/ShowDetailsCommand.java
  src/main/java/recipeio/constants/StorageConstants.java
  src/main/java/recipeio/exceptions/EmptyIndexException.java
  src/main/java/recipeio/exceptions/InvalidDescriptionException.java
  src/main/java/recipeio/exceptions/InvalidIndexException.java
  src/main/java/recipeio/recipe/Recipe.java
  src/main/java/recipeio/recipe/RecipeList.java
  src/main/java/recipeio/storage/Storage.java
  src/main/java/recipeio/ui/UI.java
  src/test/java/recipeio/RecipeIOTest.java
  src/test/java/storage/StorageTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Task
